sudo: required
dist: trusty

language: scala
scala:
- 2.12.6
jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.yarn-cache

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt scalafmt::test
  - sbt test:scalafmt::test
  - sbt test
  - sbt assembly
